name: CI PipeLine & Env Variables

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

# 1. Variables globales (al principio del archivo)
env:
  NODE_VERSION: "20"
  APP_NAME: cron-ticker

# 2. Un único bloque de JOBS para todo el archivo
jobs:

  # Primer Job: Ejecuta tus pruebas unitarias
  run-test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: Install Dependencies
        run: npm install
      
      - name: Run Tests
        run: npm test

  # Segundo Job: El ejercicio de variables del docente
  build:
    name: Build Project
    runs-on: ubuntu-latest

    env:
      BUILD_DIR: dist

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show Variables
        run: |
          echo "App: ${{ env.APP_NAME }}, Node: ${{ env.NODE_VERSION }}"

      - name: Deploye api
        run: |
          echo "Dploying with key ${{ secrets.API_KEY }}"



# variables del step
      - name: Build
        run: |
          echo "Ejecutando build simulado en la carpeta ${{ env.BUILD_DIR }} con version ${{ env.APP_VERSION }}"
        env:
          APP_VERSION: '2.0.0'